feat: add discord notification webhook
Innovate-Future-Foundation/terraform-bootstrap pull request #15
Opened 2024-12-05 03:26 UTC by henry22

- Trigger the discord notification when creating a pull request

2024-12-05 06:04 UTC, LH-Song requested changes

2024-12-05 06:04 UTC, LH-Song commented on .github/workflows/discord-notification.yml
> +        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
```suggestion
        if: github.event_name == 'pull_request' && github.event.pull_request.merged && !github.event.pull_request.draft
```

github.event.pull_request.merged is already a boolean, so no need to compare it to true. Simplifying to if: github.event.pull_request.merged makes it cleaner and easier to read. 😊

2024-12-05 06:04 UTC, LH-Song commented on .github/workflows/discord-notification.yml
> +        if: github.event_name == 'pull_request'
```suggestion
        if: github.event_name == 'pull_request' && !github.event.pull_request.draft
```
 avoids unnecessary noise. 👍

2024-12-05 06:04 UTC, LH-Song commented on .github/workflows/discord-notification.yml
> +        env:
```suggestion
        continue-on-error: true
        env:
```

add error tolerance for Discord notifications, prevents CI/CD pipeline from failing due to Discord service issues.

2024-12-05 06:04 UTC, LH-Song commented on .github/workflows/discord-notification.yml
> +        uses: actions/github-script@v6
Pin versions for better stability and security.

2024-12-05 06:04 UTC, LH-Song commented on .github/workflows/discord-notification.yml
> +        uses: Ilshidur/action-discord@master
Pin versions for better stability and security

2024-12-05 06:04 UTC, LH-Song commented on .github/workflows/discord-notification.yml
> +            **Workflow:** ${{ github.event.workflow.name }}
```suggestion
            **Workflow:** ${{ github.event.workflow.name }}
            **Branch:** ${{ github.ref_name }}
            **Environment:** ${{ github.event.workflow_run.environment }}
```
more context and easier to track environment-specific issues

2024-12-05 06:04 UTC, LH-Song commented on .github/workflows/discord-notification.yml
> +    runs-on: ubuntu-latest
```suggestion
    runs-on: ubuntu-latest
    concurrency:
        group: discord-notification-${{ github.ref }}
        cancel-in-progress: true
```

Add concurrency controls to prevent notification spam during rapid commits

2024-12-05 06:04 UTC, LH-Song commented on .github/workflows/discord-notification.yml
> +        if: github.event_name == 'push'
```suggestion
        if: github.event_name == 'push' && !contains(github.event.head_commit.message, '[skip notification]')
```
Added conditional logic to check commit messages for [skip notification] tag

Developers can now control notification flow based on commit type
Reduces noise from minor changes (docs, formatting, dependencies)

2024-12-05 22:39 UTC, dex-z approved these changes
LGTM

2024-12-10 02:12 UTC, LH-Song approved these changes
LGTM

2024-12-10 02:13 UTC, merged